// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteWebAPI.data;

#nullable disable

namespace TesteWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250402203700_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesteWebAPI.models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Teclado Mecânico",
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mouse",
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Monitor",
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Cabo HDMI",
                            Quantidade = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
